vich_uploader:
    db_driver: orm

    mappings:
        candidats:
            uri_prefix: /images/candidats
            upload_destination: "%kernel.project_dir%/public/images/candidats"
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        employeur:
            uri_prefix: /images/employeur
            upload_destination: "%kernel.project_dir%/public/images/employeur"
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        job_image:
            uri_prefix: /images/job
            upload_destination: "%kernel.project_dir%/public/images/job"
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        societe_logo:
            uri_prefix: /images/societe
            upload_destination: "%kernel.project_dir%/public/images/societe"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
